# Generated by Django 5.1.2 on 2024-11-06 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='is_approved',
        ),
    ]
