# Generated by Django 5.1.2 on 2024-11-11 01:56

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_remove_instructor_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('duration', models.CharField(max_length=50, null=True)),
                ('credits', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development'), ('Mobile App Development', 'Mobile App Development'), ('Cloud Computing', 'Cloud Computing'), ('Networking', 'Networking'), ('Database Management', 'Database Management'), ('Software Engineering', 'Software Engineering'), ('IT Project Management', 'IT Project Management'), ('Computer Science', 'Computer Science')], max_length=255, null=True)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=255, null=True)),
                ('syllabus', ckeditor.fields.RichTextField(null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
