# Generated by Django 5.1.2 on 2024-11-15 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0004_course_image_course_language_module_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
