# Generated by Django 5.1.2 on 2024-11-18 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0007_module_topic_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='topic',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='content',
            new_name='description',
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='instructors.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=200)),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('video', 'Video'), ('document', 'Document')], max_length=50)),
                ('content_data_text', models.TextField(blank=True, null=True)),
                ('content_data_video', models.URLField(blank=True, null=True)),
                ('content_data_document', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='instructors.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('progress_percentage', models.FloatField(default=0.0)),
                ('content', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.content')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='instructors.course')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'course', 'module', 'lesson', 'content')},
            },
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
