# Generated by Django 5.1.2 on 2024-11-18 15:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0008_remove_lesson_topic_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='lesson',
        ),
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('user', 'course', 'module', 'content')},
        ),
        migrations.AddField(
            model_name='content',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='instructors.module'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='Lesson',
        ),
    ]
