# Generated by Django 5.1.2 on 2024-11-22 21:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0009_remove_content_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_data_text',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
