# Generated by Django 5.1.2 on 2024-11-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0010_alter_content_content_data_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='content_data_video',
            field=models.FileField(blank=True, null=True, upload_to='contents_videos/'),
        ),
    ]
