# Generated by Django 5.1.2 on 2024-12-04 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0014_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='course',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
