# Generated by Django 5.1.2 on 2025-03-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0015_remove_cartitem_cart_remove_cartitem_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='completed_contents',
            field=models.ManyToManyField(blank=True, related_name='completed_by_students', to='instructors.content'),
        ),
    ]
