# Generated by Django 5.1.2 on 2025-03-19 15:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0016_alter_studentprogress_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentprogress',
            unique_together={('user', 'course', 'module', 'content')},
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='course_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='completed_contents',
        ),
        migrations.RemoveField(
            model_name='studentprogress',
            name='progress_percentage',
        ),
    ]
