# Generated by Django 5.0.7 on 2025-07-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0017_alter_studentprogress_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
