# Generated by Django 5.0.7 on 2025-08-19 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0021_remove_wallettransactions_instructor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallettransactions',
            name='user',
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_transactions', to='instructors.instructor'),
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wallettransactions',
            name='transaction_type',
            field=models.CharField(max_length=10),
        ),
    ]
