# Generated by Django 5.0.7 on 2025-08-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0022_remove_wallettransactions_user_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletTransactions',
        ),
    ]
