# Generated by Django 5.0.7 on 2025-09-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0025_wallettransactions_delete_instructortransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='instructor',
            name='phone',
        ),
        migrations.AddField(
            model_name='instructor',
            name='account_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='instructor',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='instructors/profile_pics/'),
        ),
    ]
