# Generated by Django 5.0.7 on 2025-09-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0026_remove_instructor_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
