# Generated by Django 5.0.7 on 2025-09-23 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0027_instructor_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='expertise',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
