# Generated by Django 5.0.7 on 2025-09-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0029_instructorwithdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructorwithdrawalrequest',
            name='source_account',
            field=models.CharField(choices=[('account_balance', 'Account Balance'), ('earnings', 'Earnings')], default='account_balance', max_length=20),
        ),
    ]
