# Generated by Django 5.0.7 on 2025-08-20 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0025_wallettransactions_delete_instructortransaction'),
        ('wallet', '0003_rename_timestamp_wallettransaction_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='instructors.instructor'),
        ),
    ]
