# Generated by Django 5.1.2 on 2024-12-04 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='quantity',
        ),
    ]
