# Generated by Django 5.1.2 on 2024-12-05 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_cartitem_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='course',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
