# Generated by Django 5.0.7 on 2025-08-19 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_wallettransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletTransaction',
        ),
    ]
