# Generated by Django 5.0.7 on 2025-08-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_wallettransaction_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallettransaction',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
