# Generated by Django 5.0.7 on 2025-09-16 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0025_wallettransactions_delete_instructortransaction'),
        ('student', '0013_rename_timestamp_wallettransaction_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallettransaction',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_transactions', to='instructors.instructor'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='transaction_type',
            field=models.CharField(choices=[('student_payment', 'Student Payment'), ('instructor_payout', 'Instructor Payout'), ('platform_revenue', 'Platform Revenue')], max_length=20),
        ),
    ]
