# Generated by Django 5.0.7 on 2025-09-22 12:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_alter_wallettransaction_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='transaction_group_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
